# Generated by Django 5.1.7 on 2025-06-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('numero_cnss', models.CharField(max_length=255, unique=True)),
                ('date_naissance', models.DateField()),
                ('adresse', models.TextField()),
            ],
        ),
    ]
